In [ ]:
#Logistic Regression is a supervised learning algorithm used to predict the probability of a class (0 or 1).
'''Example:
Spam email → Spam (1) or Not Spam (0)
Disease → Yes (1) or No (0)
Instead of giving direct output like Linear Regression, it gives probability between 0 and 1.'''
#accuracy_score is a function in scikit-learn that tells you how many predictions your model got correct overall.
#Why not Linear Regression?
'''Linear regression can give values like:
-2, 5, 10 ❌ (not valid for probability)
We need output between:
0 → class 0
1 → class 1
So we use Sigmoid Function.'''
#Sigmoid Function (Core idea)
'''y=(1/1+e^-x)
Meaning:
Converts any value into range (0,1)
If output > 0.5 → Class 1
If output < 0.5 → Class 0'''
#TYPES
#Binary Logistic Regression (Most Important)
'''Used when output has ONLY 2 classes
0 / 1
Yes / No
Spam / Not Spam
Real-life uses:
Disease detection (Yes/No)
Student pass/fail
Loan approved/rejected

Model predicts:
0 → Not Spam
1 → Spam
👉 This is Binary Logistic Regression'''
#Multinomial Logistic Regression
'''Used when output has MORE than 2 classes (no order)
No ranking or order → just categories
📊 Dataset Example: Fruit Classification
Features (X)	Fruit Type (y)
red, round	    Apple 🍎
yellow, long	Banana 🍌
green, round	Guava 🥭
Real-life uses:
Animal classification (cat, dog, lion)
Movie genre (action, comedy, horror)

How it works:
Model calculates probability for each class:
P(Apple)
P(Banana)
P(Guava)
Then chooses highest probability.'''
#Ordinal Logistic Regression
''Used when output has MORE than 2 classes WITH ORDER
Dataset Example: Exam Grades
Marks	Grade (y)
85	   A (Excellent)
70	   B (Good)
50	   C (Average)
30	   D (Fail)
D < C < B < A
Real-life uses:
Customer satisfaction (Bad → Good → Excellent)
Hotel rating (1★ to 5★)
👉 There is a ranking'''
#What is a Confusion Matrix?
'''A confusion matrix is a table that shows how well a classification model is performing by comparing:
👉 Actual values (true labels)
👉 Predicted values (model output)
It tells you where the model is correct and where it is making mistakes.
Meaning of Each Term
✅ 1. True Positive (TP)
Model predicted 1
Actually 1
✔ Correct positive prediction
✅ 2. True Negative (TN)
Model predicted 0
Actually 0
✔ Correct negative prediction
❌ 3. False Positive (FP)
Model predicted 1
Actually 0
❌ “False alarm” (Type I error)
❌ 4. False Negative (FN)
Model predicted 0
Actually 1
❌ Missed real case (Type II error)
imple Real-Life Example (Disease Test)
Patient Result	Predicted Sick	Predicted Healthy
Actually Sick	   TP	          FN
Actually Healthy	FP	          TN'''
#A classification report is a summary of how well a classification model is performing using key metrics like:
'''Precision
Recall
F1-score
Support
It is generated after prediction and helps you understand model performance for each class separately.
1. Precision
👉 Meaning:
Out of all emails predicted as spam, how many were actually spam?
Calculation:
TP = 40
FP = 5
Precision = 40 / (40 + 5) = 40 / 45 = 0.89
📌 Interpretation:
👉 When model says “spam”, it is correct 89% of the time
✔ Focus: Reduce False Positives (FP)
✔ Important when false alarms are bad

📌 2. Recall
👉 Meaning:
Out of all actual spam emails, how many did we correctly find?
Calculation:
TP = 40
FN = 10
Recall = 40 / (40 + 10) = 40 / 50 = 0.80

Interpretation:

👉 Model catches 80% of spam emails

✔ Focus: Reduce False Negatives (FN)
✔ Important when missing positive cases is dangerous
📌 3. F1 Score
👉 Meaning:
Balanced measure of Precision + Recall
Calculation:

Precision = 0.89
Recall = 0.80

F1 = 2 × (0.89 × 0.80) / (0.89 + 0.80)
F1 ≈ 2 × 0.712 / 1.69
F1 ≈ 0.84

📌 Interpretation:

👉 Overall balanced performance = 84%

✔ Used when both FP and FN matter
4. Support
👉 Meaning:

Number of actual samples in each class

In our example:
Actual Spam = TP + FN = 40 + 10 = 50
Actual Not Spam = FP + TN = 5 + 45 = 50

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
#confusion_matrix-Shows TP, TN, FP, FN
#classification_report-Shows precision, recall, F1-score, support

In [4]:
data = {
    "Hours": [1,2,3,4,5,6,7,8,9,10],
    "Pass":  [0,0,0,0,0,1,1,1,1,1]
}
df = pd.DataFrame(data)
print(df)
#Explanation
'''Hours = input feature (X)
Pass = output (y)
0 = Fail, 1 = Pass
👉 This is a binary classification dataset'''


   Hours  Pass
0      1     0
1      2     0
2      3     0
3      4     0
4      5     0
5      6     1
6      7     1
7      8     1
8      9     1
9     10     1


In [7]:
X=df[['Hours']]
y=df['Pass']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
#xplanation
xplanation
'''X → input (hours studied)
y → output (pass/fail)
80% training, 20% testing'''

In [8]:
model=LogisticRegression()
model.fit(X_train,y_train)
#Model learns pattern:
'''👉 More hours → higher chance of passing'''

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [9]:
y_pred=model.predict(X_test)
y_pred
#Explanation
#Model predicts pass/fail for test data

array([0, 0])

In [13]:
cm=confusion_matrix(y_test,y_pred)
cm
#Variable	Meaning	
#y_test	actual test labels	
#y_pred	predicted test labels
#Meaning
'''TP → correct pass prediction
TN → correct fail prediction
FP → wrongly predicted pass
FN → missed pass'''

array([[1, 0],
       [1, 0]])

In [15]:
print(accuracy_score(y_test,y_pred))


0.5


In [16]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       0.00      0.00      0.00         1

    accuracy                           0.50         2
   macro avg       0.25      0.50      0.33         2
weighted avg       0.25      0.50      0.33         2



/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this beha

In [ ]:
'''Problem Statement -12

Classification

You are working on a dataset(diesea_risk.csv) containing multiple input

features related to patient health parameters and a binary target variable

Disease_Risk. Implement a program to perform Logistic Regression for

binary classification and analyze the relationship between the input

features and the target variable. Perform the following tasks:

i. Read the given dataset into a dataframe.

ii. Split the dataset into training and testing sets in the ratio 70:30.

iii. Train a Logistic Regression model using the input features to predict

the binary target variable Disease_Risk.

iv. Determine the model coefficients and intercept.

v. Evaluate the performance of the model using accuracy, and show the

confusion matrix.

vi. Use the trained model to predict the class label for new data points.
'''

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [21]:
df=pd.read_csv('/Users/masoomsingh/Desktop/diesea_risk.csv')
df

,AGE,BMI,Glucose,Diesase_Risk
0,10,18,90,0
1,20,20,120,0
2,30,17,70,1
3,40,25,150,1
4,50,24,100,0
5,60,30,200,1


In [26]:
X=df[['AGE','BMI','Glucose']]
y=df['Diesase_Risk']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [27]:
model=LogisticRegression()
model.fit(X_train,y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [28]:
y_pred=model.predict(X_test)
y_pred

array([1, 1])

In [29]:
print(model.coef_)
print(model.intercept_)

[[ 0.47220496  0.04934278 -0.06771487]]
[-5.88200192]


In [32]:
accuracy_s=accuracy_score(y_test,y_pred)
accuracy_s


0.5

In [34]:
c_m=confusion_matrix(y_test,y_pred)
c_m

array([[0, 1],
       [0, 1]])

In [35]:
c_r=classification_report(y_test,y_pred)
c_r

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this beha

'              precision    recall  f1-score   support\n\n           0       0.00      0.00      0.00         1\n           1       0.50      1.00      0.67         1\n\n    accuracy                           0.50         2\n   macro avg       0.25      0.50      0.33         2\nweighted avg       0.25      0.50      0.33         2\n'

In [40]:
new_points=pd.DataFrame({
    'AGE':[70],
    'BMI':[35],
    'Glucose':[250]
})
df

,AGE,BMI,Glucose
0,70,35,250


In [41]:
y_pred=model.predict(new_points)
y_pred

array([1])

In [42]:
'''You are given a dataset (heart_disease.csv) containing multiple patient health parameters such as Age, Cholesterol, Blood Pressure, and Max Heart Rate, along with a binary target variable Heart_Disease (0 = No disease, 1 = Disease). Implement a Logistic Regression model to classify whether a patient has heart disease or not.
Perform the following tasks:
Tasks:
i. Create a dataset and convert it into CSV format.
ii. Read the dataset into a DataFrame.
iii. Split the dataset into training and testing sets in the ratio 75:25.
iv. Train a Logistic Regression model using input features to predict Heart_Disease.
v. Determine the model coefficients and intercept.
vi. Evaluate the model using:
Accuracy
Confusion Matrix
Classification Report
vii. Predict the class label for new patient data.
You can use features like:
Age
Cholesterol
Blood_Pressure
Max_Heart_Rate
Target:
Heart_Disease (0 or 1)
📌 🔹 Example New Data for Prediction
new_data = [    [45, 250, 140, 160],    [60, 300, 150, 120]]'''

'You are given a dataset (heart_disease.csv) containing multiple patient health parameters such as Age, Cholesterol, Blood Pressure, and Max Heart Rate, along with a binary target variable Heart_Disease (0 = No disease, 1 = Disease). Implement a Logistic Regression model to classify whether a patient has heart disease or not.\nPerform the following tasks:\nTasks:\ni. Create a dataset and convert it into CSV format.\nii. Read the dataset into a DataFrame.\niii. Split the dataset into training and testing sets in the ratio 75:25.\niv. Train a Logistic Regression model using input features to predict Heart_Disease.\nv. Determine the model coefficients and intercept.\nvi. Evaluate the model using:\nAccuracy\nConfusion Matrix\nClassification Report\nvii. Predict the class label for new patient data.\nYou can use features like:\nAge\nCholesterol\nBlood_Pressure\nMax_Heart_Rate\nTarget:\nHeart_Disease (0 or 1)\n📌 🔹 Example New Data for Prediction\nnew_data = [    [45, 250, 140, 160],    [60, 

In [44]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [67]:
df=pd.DataFrame({
    "age":[10,20,30,40,50],
    "c":[150,160,180,250,300],
    "bp":[90,100,110,200,300],
    "mhr":[90,120,150,180,200], 
    "hr":[1,0,0,1,1]
})
df


,age,c,bp,mhr,hr
0,10,150,90,90,1
1,20,160,100,120,0
2,30,180,110,150,0
3,40,250,200,180,1
4,50,300,300,200,1


In [68]:
df.to_csv("heart_disease.csv",index=False)

In [69]:
X=df[["age","c","bp","mhr"]]
y=df["hr"]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25)

In [70]:
model=LogisticRegression()
model.fit(X_train,y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [71]:
print(model.coef_)
print(model.intercept_)

[[-0.08028166 -0.0802874  -0.08027873 -0.24084279]]
[46.56368842]


In [72]:
y_pred=model.predict(X_test)
y_pred

array([0, 0])

In [73]:
acc_sc=accuracy_score(y_test,y_pred)
acc_sc

0.0

In [74]:
con_m=confusion_matrix(y_test,y_pred)
con_m

array([[0, 0],
       [2, 0]])

In [75]:
class_r=classification_report(y_test,y_pred)
class_r

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  

'              precision    recall  f1-score   support\n\n           0       0.00      0.00      0.00       0.0\n           1       0.00      0.00      0.00       2.0\n\n    accuracy                           0.00       2.0\n   macro avg       0.00      0.00      0.00       2.0\nweighted avg       0.00      0.00      0.00       2.0\n'

In [76]:
new_point=pd.DataFrame({
    "age":[70],
    "c":[60],
    "bp":[100],
    "mhr":[120],
        })
new_point


,age,c,bp,mhr
0,70,60,100,120


In [66]:
y_pred1=model.predict(new_point)
y_pred1

array([0])

In [79]:
a_S=accuracy_score(y_test,y_pred)
a_S

0.0

In [1]:
a=confusion_matrix(y_test,y_pred)
a


NameError: name 'confusion_matrix' is not defined